import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding pricing plans...');

  const plansData = [
    {
      name: 'starter',
      displayName: 'Starter',
      description: 'Perfect for small businesses getting started with CRM',
      monthlyPrice: 999,
      yearlyPrice: 9990,
      currency: 'INR',
      maxUsers: 3,
      maxContacts: 1000,
      maxCompanies: 200,
      maxDeals: 100,
      maxPipelines: 2,
      maxAutomations: 5,
      maxEmailsPerDay: 100,
      maxSmsPerDay: 50,
      maxWhatsAppPerDay: 100,
      storageGb: 5,
      modules: ['CRM', 'INBOX', 'PIPELINE'],
      features: {
        whatsapp: true,
        email: true,
        sms: false,
        voiceCalls: false,
        customFields: true,
        apiAccess: false,
        reports: true,
        advancedReports: false,
        automation: false,
        bulkImport: true,
        bulkExport: false,
        teamCollaboration: false,
        prioritySupport: false,
        customBranding: false,
        ssoIntegration: false,
        webhooks: false,
      },
      sortOrder: 1,
      badge: null,
      isActive: true,
      isPublic: true,
    },
    {
      name: 'growth',
      displayName: 'Growth',
      description: 'For growing teams that need more power and automation',
      monthlyPrice: 2999,
      yearlyPrice: 29990,
      currency: 'INR',
      maxUsers: 10,
      maxContacts: 10000,
      maxCompanies: 2000,
      maxDeals: 1000,
      maxPipelines: 5,
      maxAutomations: 25,
      maxEmailsPerDay: 500,
      maxSmsPerDay: 200,
      maxWhatsAppPerDay: 500,
      storageGb: 20,
      modules: ['CRM', 'INBOX', 'PIPELINE', 'AUTOMATION', 'ANALYTICS'],
      features: {
        whatsapp: true,
        email: true,
        sms: true,
        voiceCalls: false,
        customFields: true,
        apiAccess: true,
        reports: true,
        advancedReports: true,
        automation: true,
        bulkImport: true,
        bulkExport: true,
        teamCollaboration: true,
        prioritySupport: false,
        customBranding: false,
        ssoIntegration: false,
        webhooks: true,
      },
      sortOrder: 2,
      badge: 'Popular',
      isActive: true,
      isPublic: true,
    },
    {
      name: 'professional',
      displayName: 'Professional',
      description: 'Full-featured CRM for established businesses',
      monthlyPrice: 7999,
      yearlyPrice: 79990,
      currency: 'INR',
      maxUsers: 25,
      maxContacts: 50000,
      maxCompanies: 10000,
      maxDeals: 5000,
      maxPipelines: 10,
      maxAutomations: 100,
      maxEmailsPerDay: 2000,
      maxSmsPerDay: 1000,
      maxWhatsAppPerDay: 2000,
      storageGb: 100,
      modules: ['CRM', 'INBOX', 'PIPELINE', 'AUTOMATION', 'ANALYTICS', 'PROJECTS', 'DIALER'],
      features: {
        whatsapp: true,
        email: true,
        sms: true,
        voiceCalls: true,
        customFields: true,
        apiAccess: true,
        reports: true,
        advancedReports: true,
        automation: true,
        bulkImport: true,
        bulkExport: true,
        teamCollaboration: true,
        prioritySupport: true,
        customBranding: true,
        ssoIntegration: false,
        webhooks: true,
      },
      sortOrder: 3,
      badge: 'Best Value',
      isActive: true,
      isPublic: true,
    },
    {
      name: 'enterprise',
      displayName: 'Enterprise',
      description: 'Custom solutions for large organizations',
      monthlyPrice: 19999,
      yearlyPrice: 199990,
      currency: 'INR',
      maxUsers: null,
      maxContacts: null,
      maxCompanies: null,
      maxDeals: null,
      maxPipelines: null,
      maxAutomations: null,
      maxEmailsPerDay: null,
      maxSmsPerDay: null,
      maxWhatsAppPerDay: null,
      storageGb: 500,
      modules: ['CRM', 'INBOX', 'PIPELINE', 'AUTOMATION', 'ANALYTICS', 'PROJECTS', 'DIALER', 'BROADCASTS'],
      features: {
        whatsapp: true,
        email: true,
        sms: true,
        voiceCalls: true,
        customFields: true,
        apiAccess: true,
        reports: true,
        advancedReports: true,
        automation: true,
        bulkImport: true,
        bulkExport: true,
        teamCollaboration: true,
        prioritySupport: true,
        customBranding: true,
        ssoIntegration: true,
        webhooks: true,
        dedicatedSupport: true,
        customIntegrations: true,
        onPremise: true,
      },
      sortOrder: 4,
      badge: null,
      isActive: true,
      isPublic: true,
    },
  ];

  for (const plan of plansData) {
    const result = await prisma.plan.upsert({
      where: { name: plan.name },
      update: {
        displayName: plan.displayName,
        description: plan.description,
        monthlyPrice: plan.monthlyPrice,
        yearlyPrice: plan.yearlyPrice,
        currency: plan.currency,
        maxUsers: plan.maxUsers,
        maxContacts: plan.maxContacts,
        maxCompanies: plan.maxCompanies,
        maxDeals: plan.maxDeals,
        maxPipelines: plan.maxPipelines,
        maxAutomations: plan.maxAutomations,
        maxEmailsPerDay: plan.maxEmailsPerDay,
        maxSmsPerDay: plan.maxSmsPerDay,
        maxWhatsAppPerDay: plan.maxWhatsAppPerDay,
        storageGb: plan.storageGb,
        modules: plan.modules,
        features: plan.features,
        sortOrder: plan.sortOrder,
        badge: plan.badge,
        isActive: plan.isActive,
        isPublic: plan.isPublic,
      },
      create: plan,
    });
    console.log(`  ${result.displayName} - ₹${result.monthlyPrice}/month`);
  }

  console.log('\n✅ Created', plansData.length, 'pricing plans');
}

main()
  .catch((e) => {
    console.error('Error seeding plans:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
